name: Deploy na WebGlobe SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Stiahnuť kód
        uses: actions/checkout@v4

      - name: Nahrať na WebGlobe cez SFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" sftp://${{ secrets.FTP_SERVER }}:222 <<EOF
          set sftp:auto-confirm yes
          mirror -R --verbose \
            --exclude-glob .git* \
            --exclude-glob .github/ \
            --exclude-glob README* \
            --exclude-glob *.md \
            ./ ./public_html/
          bye
          EOF